# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/nachiket/Documents/qt5-workspace/chess-AI

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/nachiket/Documents/qt5-workspace/chess-AI

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nachiket/Documents/qt5-workspace/chess-AI/CMakeFiles /home/nachiket/Documents/qt5-workspace/chess-AI/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nachiket/Documents/qt5-workspace/chess-AI/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named chess-AI

# Build rule for target.
chess-AI: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 chess-AI
.PHONY : chess-AI

# fast build rule for target.
chess-AI/fast:
	$(MAKE) -f CMakeFiles/chess-AI.dir/build.make CMakeFiles/chess-AI.dir/build
.PHONY : chess-AI/fast

#=============================================================================
# Target rules for targets named chess-AI_autogen

# Build rule for target.
chess-AI_autogen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 chess-AI_autogen
.PHONY : chess-AI_autogen

# fast build rule for target.
chess-AI_autogen/fast:
	$(MAKE) -f CMakeFiles/chess-AI_autogen.dir/build.make CMakeFiles/chess-AI_autogen.dir/build
.PHONY : chess-AI_autogen/fast

board.o: board.cpp.o

.PHONY : board.o

# target to build an object file
board.cpp.o:
	$(MAKE) -f CMakeFiles/chess-AI.dir/build.make CMakeFiles/chess-AI.dir/board.cpp.o
.PHONY : board.cpp.o

board.i: board.cpp.i

.PHONY : board.i

# target to preprocess a source file
board.cpp.i:
	$(MAKE) -f CMakeFiles/chess-AI.dir/build.make CMakeFiles/chess-AI.dir/board.cpp.i
.PHONY : board.cpp.i

board.s: board.cpp.s

.PHONY : board.s

# target to generate assembly for a file
board.cpp.s:
	$(MAKE) -f CMakeFiles/chess-AI.dir/build.make CMakeFiles/chess-AI.dir/board.cpp.s
.PHONY : board.cpp.s

boardtile.o: boardtile.cpp.o

.PHONY : boardtile.o

# target to build an object file
boardtile.cpp.o:
	$(MAKE) -f CMakeFiles/chess-AI.dir/build.make CMakeFiles/chess-AI.dir/boardtile.cpp.o
.PHONY : boardtile.cpp.o

boardtile.i: boardtile.cpp.i

.PHONY : boardtile.i

# target to preprocess a source file
boardtile.cpp.i:
	$(MAKE) -f CMakeFiles/chess-AI.dir/build.make CMakeFiles/chess-AI.dir/boardtile.cpp.i
.PHONY : boardtile.cpp.i

boardtile.s: boardtile.cpp.s

.PHONY : boardtile.s

# target to generate assembly for a file
boardtile.cpp.s:
	$(MAKE) -f CMakeFiles/chess-AI.dir/build.make CMakeFiles/chess-AI.dir/boardtile.cpp.s
.PHONY : boardtile.cpp.s

chess-AI_autogen/mocs_compilation.o: chess-AI_autogen/mocs_compilation.cpp.o

.PHONY : chess-AI_autogen/mocs_compilation.o

# target to build an object file
chess-AI_autogen/mocs_compilation.cpp.o:
	$(MAKE) -f CMakeFiles/chess-AI.dir/build.make CMakeFiles/chess-AI.dir/chess-AI_autogen/mocs_compilation.cpp.o
.PHONY : chess-AI_autogen/mocs_compilation.cpp.o

chess-AI_autogen/mocs_compilation.i: chess-AI_autogen/mocs_compilation.cpp.i

.PHONY : chess-AI_autogen/mocs_compilation.i

# target to preprocess a source file
chess-AI_autogen/mocs_compilation.cpp.i:
	$(MAKE) -f CMakeFiles/chess-AI.dir/build.make CMakeFiles/chess-AI.dir/chess-AI_autogen/mocs_compilation.cpp.i
.PHONY : chess-AI_autogen/mocs_compilation.cpp.i

chess-AI_autogen/mocs_compilation.s: chess-AI_autogen/mocs_compilation.cpp.s

.PHONY : chess-AI_autogen/mocs_compilation.s

# target to generate assembly for a file
chess-AI_autogen/mocs_compilation.cpp.s:
	$(MAKE) -f CMakeFiles/chess-AI.dir/build.make CMakeFiles/chess-AI.dir/chess-AI_autogen/mocs_compilation.cpp.s
.PHONY : chess-AI_autogen/mocs_compilation.cpp.s

debugwindow.o: debugwindow.cpp.o

.PHONY : debugwindow.o

# target to build an object file
debugwindow.cpp.o:
	$(MAKE) -f CMakeFiles/chess-AI.dir/build.make CMakeFiles/chess-AI.dir/debugwindow.cpp.o
.PHONY : debugwindow.cpp.o

debugwindow.i: debugwindow.cpp.i

.PHONY : debugwindow.i

# target to preprocess a source file
debugwindow.cpp.i:
	$(MAKE) -f CMakeFiles/chess-AI.dir/build.make CMakeFiles/chess-AI.dir/debugwindow.cpp.i
.PHONY : debugwindow.cpp.i

debugwindow.s: debugwindow.cpp.s

.PHONY : debugwindow.s

# target to generate assembly for a file
debugwindow.cpp.s:
	$(MAKE) -f CMakeFiles/chess-AI.dir/build.make CMakeFiles/chess-AI.dir/debugwindow.cpp.s
.PHONY : debugwindow.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/chess-AI.dir/build.make CMakeFiles/chess-AI.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/chess-AI.dir/build.make CMakeFiles/chess-AI.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/chess-AI.dir/build.make CMakeFiles/chess-AI.dir/main.cpp.s
.PHONY : main.cpp.s

minmaxabp.o: minmaxabp.cpp.o

.PHONY : minmaxabp.o

# target to build an object file
minmaxabp.cpp.o:
	$(MAKE) -f CMakeFiles/chess-AI.dir/build.make CMakeFiles/chess-AI.dir/minmaxabp.cpp.o
.PHONY : minmaxabp.cpp.o

minmaxabp.i: minmaxabp.cpp.i

.PHONY : minmaxabp.i

# target to preprocess a source file
minmaxabp.cpp.i:
	$(MAKE) -f CMakeFiles/chess-AI.dir/build.make CMakeFiles/chess-AI.dir/minmaxabp.cpp.i
.PHONY : minmaxabp.cpp.i

minmaxabp.s: minmaxabp.cpp.s

.PHONY : minmaxabp.s

# target to generate assembly for a file
minmaxabp.cpp.s:
	$(MAKE) -f CMakeFiles/chess-AI.dir/build.make CMakeFiles/chess-AI.dir/minmaxabp.cpp.s
.PHONY : minmaxabp.cpp.s

piece.o: piece.cpp.o

.PHONY : piece.o

# target to build an object file
piece.cpp.o:
	$(MAKE) -f CMakeFiles/chess-AI.dir/build.make CMakeFiles/chess-AI.dir/piece.cpp.o
.PHONY : piece.cpp.o

piece.i: piece.cpp.i

.PHONY : piece.i

# target to preprocess a source file
piece.cpp.i:
	$(MAKE) -f CMakeFiles/chess-AI.dir/build.make CMakeFiles/chess-AI.dir/piece.cpp.i
.PHONY : piece.cpp.i

piece.s: piece.cpp.s

.PHONY : piece.s

# target to generate assembly for a file
piece.cpp.s:
	$(MAKE) -f CMakeFiles/chess-AI.dir/build.make CMakeFiles/chess-AI.dir/piece.cpp.s
.PHONY : piece.cpp.s

rules.o: rules.cpp.o

.PHONY : rules.o

# target to build an object file
rules.cpp.o:
	$(MAKE) -f CMakeFiles/chess-AI.dir/build.make CMakeFiles/chess-AI.dir/rules.cpp.o
.PHONY : rules.cpp.o

rules.i: rules.cpp.i

.PHONY : rules.i

# target to preprocess a source file
rules.cpp.i:
	$(MAKE) -f CMakeFiles/chess-AI.dir/build.make CMakeFiles/chess-AI.dir/rules.cpp.i
.PHONY : rules.cpp.i

rules.s: rules.cpp.s

.PHONY : rules.s

# target to generate assembly for a file
rules.cpp.s:
	$(MAKE) -f CMakeFiles/chess-AI.dir/build.make CMakeFiles/chess-AI.dir/rules.cpp.s
.PHONY : rules.cpp.s

theme.o: theme.cpp.o

.PHONY : theme.o

# target to build an object file
theme.cpp.o:
	$(MAKE) -f CMakeFiles/chess-AI.dir/build.make CMakeFiles/chess-AI.dir/theme.cpp.o
.PHONY : theme.cpp.o

theme.i: theme.cpp.i

.PHONY : theme.i

# target to preprocess a source file
theme.cpp.i:
	$(MAKE) -f CMakeFiles/chess-AI.dir/build.make CMakeFiles/chess-AI.dir/theme.cpp.i
.PHONY : theme.cpp.i

theme.s: theme.cpp.s

.PHONY : theme.s

# target to generate assembly for a file
theme.cpp.s:
	$(MAKE) -f CMakeFiles/chess-AI.dir/build.make CMakeFiles/chess-AI.dir/theme.cpp.s
.PHONY : theme.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... chess-AI"
	@echo "... chess-AI_autogen"
	@echo "... board.o"
	@echo "... board.i"
	@echo "... board.s"
	@echo "... boardtile.o"
	@echo "... boardtile.i"
	@echo "... boardtile.s"
	@echo "... chess-AI_autogen/mocs_compilation.o"
	@echo "... chess-AI_autogen/mocs_compilation.i"
	@echo "... chess-AI_autogen/mocs_compilation.s"
	@echo "... debugwindow.o"
	@echo "... debugwindow.i"
	@echo "... debugwindow.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... minmaxabp.o"
	@echo "... minmaxabp.i"
	@echo "... minmaxabp.s"
	@echo "... piece.o"
	@echo "... piece.i"
	@echo "... piece.s"
	@echo "... rules.o"
	@echo "... rules.i"
	@echo "... rules.s"
	@echo "... theme.o"
	@echo "... theme.i"
	@echo "... theme.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

